---

- name: Install MongoDB (Homebrew)
  homebrew: name=mongodb state=present
  become: true
  become_user: "{{ mongo_dev_homebrew_user }}"
  when: ansible_pkg_mgr == 'homebrew'

- name: Start MongoDB (Homebrew)
  shell: su - {{ mongo_dev_homebrew_user }} -c "{{ mongo_dev_homebrew_bin }} services start mongodb"
  register: result
  changed_when: result.rc != 0
  when: ansible_pkg_mgr == 'homebrew'

# Unsupported package managers
- fail: msg="{{ ansible_pkg_mgr }} is not a supported package manager (Homebrew is supported)"
  when: ansible_pkg_mgr != 'homebrew'
